### ISSUE TITLE
Refactor Arrow making use of Arrow meta features [Draft ticket]

### ISSUE THREAD

**Issue by danimontoya** [arrow-kt/arrow-core#246]
Since Arrow Meta is becoming stable we can start the integration into Arrow Core so we can make a nice refactor of current encoding by making use of all the Arrow meta features.

These are the first steps to get to the goal:

- [x] Enable the Arrow meta compiler plugin, so we can add it to the IDE. [Here is the setup guide](https://meta.arrow-kt.io/setup.html)
- [ ] Migrate the prelude module from meta into Arrow core, so we can make use of type proofs, Tuples, Unions, Refined types and so on.
- [ ] Refactor typeclasses. Make use of Coercion/Extension/Given type proofs. Start refactor with Semigroup.
- [ ] Deprecate current definition for Tuples and make use of the encoding done in Meta.
- [ ] Benchmark Union types vs Sealed classes
- [ ] More to be added here
